apiVersion: microservice.slime.io/v1alpha1
kind: SlimeBoot
metadata:
  name: example-slimeboot
spec:
  # Default values copied from <project_dir>/helm-charts/slimeboot/values.yaml\
  module:
    - limiter:
        enable: true
        backend: 1
      plugin:
        enable: true
      fence:
        enable: true
        wormholePort:
          - "80"
      global:
        service: app
        istioNamespace: istio-system
        globalSidecarNamespace: mesh-operator
      name: slime-all

  
